### ISSUE TITLE
Google Sign in fails with JWT:InvalidatError

### ISSUE THREAD

**Issue by vik-y** [zense/Anonymous-Polling-App#11]
JWT::InvalidIatError
<img width="852" alt="screen shot 2018-01-22 at 12 29 57 pm" src="https://user-images.githubusercontent.com/6398563/35208813-34755eb2-ff70-11e7-9de3-85fe67aba48f.png">

Is anyone else facing this issue?

**Comment by asquare14** [comment]
Satvik said he faced this, but we tried for some more people. It was
working fine. I guess, it's because the google privacy settings are too
strict.

**Comment by vik-y** [comment]
It has nothing to do with privacy settings, it's an omniauth version issue. Might require some workaround. 

@arkokoley - Do you have any idea about this?

**Comment by arkokoley** [comment]
add ` :skip_jwt => true,` to the file `config/initializers/devise.rb`

example:
[https://github.com/zense/rails_oauth_starter/blob/master/config/initializers/devise.rb#L281-L288](https://github.com/zense/rails_oauth_starter/blob/master/config/initializers/devise.rb#L281-L288)

**Comment by arkokoley** [comment]
@aSquare14  whats the status of this issue?

**Comment by asquare14** [comment]
We did not use devise, we did it using a sessions controller. Just OAuth.

**Comment by asquare14** [comment]
https://github.com/aSquare14/Anonymous-Polling-App/blob/23cae04043fe18ec131b64a0e528129642dd696d/config/initializers/omniauth.rb#L3
This should work!
Please close after review.
