### ISSUE TITLE
sqlite db files present in version control

### ISSUE THREAD

**Issue by vik-y** [zense/Anonymous-Polling-App#12]
Check the db folder. In that the sqlite files are added in version control. Sqlite files should not be a part of version control. You might consider using gitignore

**Comment by arkokoley** [comment]
@aSquare14  whats the status of this issue?

**Comment by asquare14** [comment]
Latest commit fixes this issue. :)
d4ba0875ecd9c09267fbb8704c3cfd1d154418df
Please close after review !

**Comment by asquare14** [comment]
Done
