### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by asquare14** [zense/Anonymous-Polling-App#14]
Dockerize this App

**Comment by ffreitasalves** [comment]
Can I help with that?

**Comment by adishegde** [comment]
This app has been dockerized about a month ago. Check the `dockerize` branch. Also the app needs to be dockerized so that it is compatible with the setup of the current zense VM (which is what the `dockerize` branch does).

**Comment by ffreitasalves** [comment]
Beautiful code!
